#!/usr/bin/env bash
set -euo pipefail

dirs=(
  "app/Controllers"
  "app/Core"
  "app/Middleware"
  "app/Models"
  "app/Services"
  "bootstrap"
  "config"
  "database/migrations"
  "database/seeds"
  "public/assets/css"
  "public/assets/js"
  "public/assets/images"
  "resources/views/layouts"
  "resources/views/partials"
  "resources/views/auth"
  "resources/views/dashboard"
  "resources/views/departments"
  "resources/views/tasks"
  "resources/views/errors"
  "routes"
  "storage/cache"
  "storage/logs"
  "storage/uploads"
  "tests/Feature"
  "tests/Unit"
)

department_dirs=(
  "resources/views/departments/general-management"
  "resources/views/departments/finance-accounting"
  "resources/views/departments/human-resources"
  "resources/views/departments/sales"
  "resources/views/departments/marketing"
  "resources/views/departments/operations"
  "resources/views/departments/production-service-delivery"
  "resources/views/departments/supply-chain-logistics-procurement"
  "resources/views/departments/information-technology"
  "resources/views/departments/research-development"
  "resources/views/departments/customer-service-support"
  "resources/views/departments/legal-compliance"
  "resources/views/departments/quality-management"
)

files=(
  ".env.example"
  ".gitignore"
  "app/Controllers/AuthController.php"
  "app/Controllers/DashboardController.php"
  "app/Controllers/DepartmentController.php"
  "app/Controllers/TaskController.php"
  "app/Controllers/UserController.php"
  "app/Core/App.php"
  "app/Core/Controller.php"
  "app/Core/Database.php"
  "app/Core/Request.php"
  "app/Core/Response.php"
  "app/Core/Router.php"
  "app/Core/Session.php"
  "app/Core/View.php"
  "app/Middleware/AuthMiddleware.php"
  "app/Middleware/CsrfMiddleware.php"
  "app/Middleware/DepartmentAccessMiddleware.php"
  "app/Models/Department.php"
  "app/Models/Role.php"
  "app/Models/Task.php"
  "app/Models/TaskComment.php"
  "app/Models/User.php"
  "app/Services/AuthService.php"
  "app/Services/DepartmentService.php"
  "app/Services/TaskService.php"
  "app/Services/UserService.php"
  "bootstrap/app.php"
  "config/app.php"
  "config/auth.php"
  "config/database.php"
  "config/departments.php"
  "database/migrations/001_create_users_table.sql"
  "database/migrations/002_create_roles_table.sql"
  "database/migrations/003_create_departments_table.sql"
  "database/migrations/004_create_department_user_table.sql"
  "database/migrations/005_create_tasks_table.sql"
  "database/migrations/006_create_task_comments_table.sql"
  "database/seeds/001_departments.sql"
  "database/seeds/002_roles.sql"
  "database/seeds/003_admin_user.sql"
  "public/.htaccess"
  "public/index.php"
  "public/assets/css/app.css"
  "public/assets/js/app.js"
  "public/assets/images/.gitkeep"
  "resources/views/layouts/app.php"
  "resources/views/partials/alerts.php"
  "resources/views/partials/footer.php"
  "resources/views/partials/header.php"
  "resources/views/partials/sidebar.php"
  "resources/views/auth/login.php"
  "resources/views/dashboard/index.php"
  "resources/views/departments/index.php"
  "resources/views/tasks/create.php"
  "resources/views/tasks/edit.php"
  "resources/views/tasks/index.php"
  "resources/views/tasks/show.php"
  "resources/views/errors/404.php"
  "resources/views/errors/500.php"
  "routes/api.php"
  "routes/web.php"
  "storage/cache/.gitkeep"
  "storage/logs/.gitkeep"
  "storage/uploads/.gitkeep"
  "tests/Feature/AuthenticationTest.php"
  "tests/Feature/DepartmentPagesTest.php"
  "tests/Feature/TaskWorkflowTest.php"
  "tests/Unit/DepartmentServiceTest.php"
  "tests/Unit/TaskServiceTest.php"
  "tests/Unit/UserServiceTest.php"
)

department_files=(
  "resources/views/departments/general-management/index.php"
  "resources/views/departments/finance-accounting/index.php"
  "resources/views/departments/human-resources/index.php"
  "resources/views/departments/sales/index.php"
  "resources/views/departments/marketing/index.php"
  "resources/views/departments/operations/index.php"
  "resources/views/departments/production-service-delivery/index.php"
  "resources/views/departments/supply-chain-logistics-procurement/index.php"
  "resources/views/departments/information-technology/index.php"
  "resources/views/departments/research-development/index.php"
  "resources/views/departments/customer-service-support/index.php"
  "resources/views/departments/legal-compliance/index.php"
  "resources/views/departments/quality-management/index.php"
)

for dir in "${dirs[@]}"; do
  mkdir -p "$dir"
done

for dir in "${department_dirs[@]}"; do
  mkdir -p "$dir"
done

for file in "${files[@]}"; do
  touch "$file"
done

for file in "${department_files[@]}"; do
  touch "$file"
done